### ISSUE TITLE
Websocket to be run in non-browser environment should be added as standard

### ISSUE THREAD

**Issue by nattelog** [whitelizard/archmage-client#1]
Hi,

I see in your [tests](https://github.com/whitelizard/archmage-client/blob/master/src/test/archmage-session.js#L5-L7) that it is possible to pass in a custom ws client when using this library in non-browser environments. However, in the archmage portal where this library is used it is not possible for a test driver to pass in this argument. The archmage-client is connecting as soon as the library is imported and when the connection is made in a non-browser environment there is no socket to be created. 

My suggestion is that `createWebSocket` in [ws-client.js](https://github.com/whitelizard/archmage-client/blob/master/src/ws-client.js#L16-L23) is extended by with the same functionality as in the test, i.e:

``` javascript
import { w3cwebsocket } from 'websocket';

function createWebSocket(url, protocols, customWsClient) {
  const urlOk = /wss?:\/\//.exec(url);
  if (!urlOk) {
    throw new Error('Invalid url provided');
  }
  // add w3cwebsocket here at the end
  const Socket = customWsClient || window.WebSocket || window.MozWebSocket || w3cwebsocket;
  return new Socket(url, protocols || undefined);
}
```

**Comment by whitelizard** [comment]
node.js has this `global` global variable, instead of `window`, so the solution I made was to create an abstracted global variable `globalVar` like so:

```
const globalVar = typeof global !== 'undefined'
  ? global
  : (typeof window !== 'undefined' ? window : {});
```
